Repository prgrms-fe-devcourse/FEDC5_STYLED_sehee, pull requests merged in 2024-01, with the labels that each got.

#19 Feat: Theme 색상 추가
  src/Styles/Theme.ts
Labels: 💧 순한맛

#27 Fix: Button 컴포넌트 ref 및 클릭이벤트 props 수정
  src/Components/Base/Button/index.tsx
  src/Components/Base/Button/type.ts
Labels: Fix

#26 Feat: Input 컴포넌트 ref 기능 추가
  src/Components/Base/Input/index.tsx
  src/Components/Base/Input/type.ts
Labels: Feat

#28 Refactor: Button 컴포넌트 코드리뷰 피드백 반영
  src/Components/Base/Button/index.tsx
  src/Components/Base/Button/style.ts
  src/Components/Base/Button/type.ts
Labels: Fix

#24 Feat: ImageUpload 컴포넌트 구현
  src/Components/Common/ImageUpload/index.tsx
  src/Components/Common/ImageUpload/style.ts
  src/Components/Common/ImageUpload/type.ts
  src/Pages/HomePage/index.tsx
Labels: Feat

#29 Feat: Alert 컴포넌트 구현
  src/Components/Common/Alert/index.tsx
  src/Components/Common/Alert/style.ts
  src/Components/Common/Alert/type.ts
Labels: Feat

#13 Feat: 공용 API 함수 구현
  src/Api/axiosInstance.ts
  src/Api/ex.md
  src/Api/handleError.ts
  src/Api/interceptors.ts
  src/Constants/Api.ts
  src/Constants/ex.md
  src/Services/Auth/index.ts
  src/Services/Channel/index.ts
  src/Services/Comment/index.ts
  src/Services/Follow/index.ts
  src/Services/Like/index.ts
  src/Services/Message/index.ts
  src/Services/Notification/index.ts
  src/Services/Post/index.ts
  src/Services/Search/index.ts
  src/Services/Setting/index.ts
  src/Services/User/index.ts
  src/Services/ex.md
  src/Types/Request/index.ts
  src/main.tsx
  src/vite-env.d.ts
Labels: Feat

#34 Feat: 다크모드 전역 상태 관리 기능 추가
  src/App.tsx
  src/Stores/DarkMode/index.ts
  src/Stores/DarkMode/type.ts
  src/Stores/ex.md
  src/Stores/index.ts
Labels: Feat

#37 Feat: 채널 생성 및 상수화
  src/Constants/Channels.ts
Labels: Feat

#40 Fix: useForm onChange 이벤트 시 에러 처리 기능 수정
  src/Hooks/UseForm/index.ts
  src/Hooks/UseForm/type.ts
  src/Hooks/index.ts
Labels: Fix

#36 Feat: 로그인 페이지 레이아웃
  src/Assets/Images/STYLED-logo-black.png
  src/Assets/Images/STYLED-logo-white.png
  src/Components/Common/HistoryBackButton/index.tsx
  src/Components/Common/HistoryBackButton/type.ts
  src/Components/Common/Logo/index.tsx
  src/Components/Common/Logo/style.ts
  src/Components/Common/Logo/type.ts
  src/Components/Login/LoginForm/index.tsx
  src/Components/Login/LoginForm/style.ts
  src/Components/Login/LoginForm/type.ts
  src/Components/Login/LoginForm/validateLogin.ts
  src/Components/Login/MoveToSignUpButton/index.tsx
  src/Pages/LoginPage/index.tsx
  src/Pages/LoginPage/style.ts
  src/Pages/index.ts
  src/Routes/Router.tsx
  src/Utils/validateEmail.ts
Labels: Feat

#30 Feat: Badge 컴포넌트 구현
  src/Components/Base/Avatar/index.tsx
  src/Components/Base/Avatar/style.ts
  src/Components/Base/Avatar/type.ts
  src/Components/Base/Badge/index.tsx
  src/Components/Base/Badge/style.ts
  src/Components/Base/Badge/type.ts
Labels: Feat

#31 Feat: DropDown 컴포넌트 구현
  src/Components/Common/DropDown/index.tsx
  src/Components/Common/DropDown/style.ts
  src/Components/Common/DropDown/type.ts
  src/Styles/Theme.ts
Labels: Feat

#35 Feat: Spinner 컴포넌트 구현
  src/Components/Base/Spinner/index.tsx
  src/Components/Base/Spinner/style.ts
  src/Components/Base/Spinner/type.ts
  src/Styles/Animation.ts
Labels: Feat

#38 Feat: Skeleton 컴포넌트 구현
  src/Components/Base/Skeleton/index.tsx
  src/Components/Base/Skeleton/style.ts
  src/Components/Base/Skeleton/type.ts
  src/Styles/Animation.ts
Labels: Feat

#41 Feat: 세션스토리지 커스텀 훅 기능 추가
  src/Hooks/UseSessionStorage/index.ts
  src/Hooks/index.ts
Labels: Feat

#42 Fix: Modal 컴포넌트 wrapper 너비 및 높이 수정
  src/Components/Common/Modal/style.ts
Labels: Fix

#45 Feat: 로그인 기능 개발
  src/Api/interceptors.ts
  src/Components/Common/HistoryBackButton/index.tsx
  src/Components/Common/Logo/index.tsx
  src/Components/Login/LoginForm/index.tsx
  src/Components/Login/LoginForm/type.ts
  src/Components/Login/MoveToSignUpButton/index.tsx
  src/Hooks/UseForm/index.ts
  src/Hooks/UseForm/type.ts
  src/Pages/LoginPage/index.tsx
  src/Stores/AuthUser/index.ts
  src/Stores/AuthUser/type.ts
  src/Stores/DarkMode/index.ts
  src/Styles/Theme.ts
Labels: Feat, Fix

#44 Feat: HomePage(메인페이지) 레이아웃 및 기본 기능 구현
  src/Components/Common/SearchBar/type.ts
  src/Constants/Channels.ts
  src/Pages/HomePage/index.tsx
  src/Pages/HomePage/style.ts
  src/Pages/HomePage/type.ts
Labels: Feat

#43 Feat: UserCard 공용 컴포넌트 구현
  src/Components/Common/UserCard/index.tsx
  src/Components/Common/UserCard/style.ts
  src/Components/Common/UserCard/type.ts
Labels: Feat

#39 Feat: ImageCard 컴포넌트
  src/Assets/Images/STYLED-logo-black.png
  src/Components/Common/ImageCard/index.tsx
  src/Components/Common/ImageCard/style.ts
  src/Components/Common/ImageCard/type.ts
Labels: Feat

#49 Fix: Modal 컴포넌트 렌더링 포탈 및 props 일부 수정
  src/Components/Common/Modal/index.tsx
  src/Components/Common/Modal/style.ts
  src/Components/Common/Modal/type.ts
Labels: Fix

#51 Feat: Modal 다크모드 props 추가
  src/Components/Common/Modal/index.tsx
  src/Components/Common/Modal/style.ts
  src/Components/Common/Modal/type.ts
Labels: Feat

#52 Fix: fixLoginForm
  src/Components/Login/LoginForm/index.tsx
  src/Components/Login/LoginForm/validateLogin.ts
  src/Hooks/UseForm/index.ts
Labels: Fix

#53 Refactor: DropDown 컴포넌트 리팩토링
  src/Components/Common/DropDown/index.tsx
  src/Components/Common/DropDown/style.ts
  src/Components/Common/DropDown/type.ts
Labels: Refactor

#46 Feat: 회원가입 페이지
  src/Components/Base/Button/style.ts
  src/Components/Base/Input/style.ts
  src/Components/SignUp/SignUpForm/index.tsx
  src/Components/SignUp/SignUpForm/style.ts
  src/Components/SignUp/SignUpForm/type.ts
  src/Components/SignUp/SignUpForm/validateSignUp.ts
  src/Constants/Message.ts
  src/Pages/SignUpPage/index.tsx
  src/Pages/SignUpPage/style.ts
  src/Pages/index.ts
  src/Routes/Router.tsx
Labels: Feat

#54 Fix: icon 클래스 추가
  src/Components/Base/Icon/index.tsx
  src/Components/Base/Icon/type.ts
Labels: Fix

#48 Feat: 전체 사용자 목록 조회
  package-lock.json
  package.json
  src/Components/UserManager/UserItem/index.tsx
  src/Components/UserManager/UserItem/style.ts
  src/Components/UserManager/UserItem/type.ts
  src/Components/UserManager/UserList/index.tsx
  src/Components/UserManager/UserList/style.ts
  src/Components/UserManager/UserList/type.ts
  src/Components/UserManager/UserSearchForm/index.tsx
  src/Components/UserManager/index.tsx
  src/Components/UserManager/style.ts
  src/Constants/queryKeys.ts
  src/Pages/HomePage/index.tsx
  src/Pages/HomePage/style.ts
Labels: Feat

#32 Feat: Header 컴포넌트
  src/App.tsx
  src/Assets/Images/STYLED-logo-white.png
  src/Components/Common/DropDown/index.tsx
  src/Components/Common/Header/HeaderLogo/index.tsx
  src/Components/Common/Header/HeaderLogo/style.ts
  src/Components/Common/Header/HeaderTab/LinkButton/index.tsx
  src/Components/Common/Header/HeaderTab/LinkButton/type.ts
  src/Components/Common/Header/HeaderTab/LoginButton/index.tsx
  src/Components/Common/Header/HeaderTab/ModalButton/index.tsx
  src/Components/Common/Header/HeaderTab/ModalButton/type.ts
  src/Components/Common/Header/HeaderTab/index.tsx
  src/Components/Common/Header/HeaderTab/style.ts
  src/Components/Common/Header/index.tsx
  src/Components/Common/Header/style.ts
  src/Components/Common/Header/type.ts
  src/Components/Common/Modal/AlarmModal/index.tsx
  src/Pages/AddPostPage/PostModal/index.tsx
  src/Pages/AddPostPage/index.tsx
  src/Pages/DirectMessagePage/index.tsx
  src/Pages/EditPasswordPage/PasswordModal/index.tsx
  src/Pages/EditPasswordPage/index.tsx
  src/Pages/ProfilePage/index.tsx
  src/Pages/SearchPage/SearchModal/index.tsx
  src/Pages/SearchPage/index.tsx
  src/Pages/index.ts
  src/Routes/Router.tsx
  src/Stores/Tab/index.ts
  src/Stores/Tab/type.ts
  src/main.tsx
Labels: Feat

#47 Feat: 다이렉트 메세지 페이지
  package-lock.json
  package.json
  src/Components/Base/Button/style.ts
  src/Components/Base/Skeleton/type.ts
  src/Components/Common/Alert/type.ts
  src/Components/Common/SearchBar/style.tsx
  src/Components/Common/UserCard/index.tsx
  src/Components/Common/UserCard/style.ts
  src/Components/Common/UserCard/type.ts
  src/Components/DirectMessage/ConversationList/index.tsx
  src/Components/DirectMessage/ConversationList/style.ts
  src/Components/DirectMessage/ConversationList/type.ts
  src/Components/DirectMessage/MessageItem/index.tsx
  src/Components/DirectMessage/MessageItem/style.ts
  src/Components/DirectMessage/MessageList/index.tsx
  src/Components/DirectMessage/MessageList/style.ts
  src/Components/DirectMessage/MessageList/type.ts
  src/Components/DirectMessage/MessageModal/index.tsx
  src/Components/DirectMessage/MessageModal/style.ts
  src/Components/DirectMessage/MessageModal/type.ts
  src/Components/DirectMessage/Skeleton/index.tsx
  src/Components/DirectMessage/Skeleton/style.ts
  src/Components/DirectMessage/Skeleton/type.ts
  src/Hooks/Api/Message/index.ts
  src/Pages/DirectMessagePage/index.tsx
  src/Pages/DirectMessagePage/style.ts
  src/Routes/Router.tsx
  src/Services/Notification/index.ts
  src/Types/UserType.ts
  src/Utils/UTCtoKST.ts
  src/Utils/ex.md
Labels: Feat

#57 Feat: Theme 모드 세션스토리지 저장
  src/Constants/storage.ts
  src/Stores/DarkMode/index.ts
Labels: Feat

#58 Feat: 메인 페이지 포스트 무한 스크롤 구현
  src/Pages/HomePage/index.tsx
  src/Pages/HomePage/style.ts
  src/Utils/checkSuperUser.ts
Labels: Feat

#56 Feat: 알림 목록 조회
  src/Components/Common/SkeletonList/index.tsx
  src/Components/Common/SkeletonList/style.ts
  src/Components/Common/SkeletonList/type.ts
  src/Components/NotificationModal/CategoryItem/index.tsx
  src/Components/NotificationModal/CategoryItem/style.ts
  src/Components/NotificationModal/CategoryItem/type.ts
  src/Components/NotificationModal/CategoryList/index.tsx
  src/Components/NotificationModal/CategoryList/style.ts
  src/Components/NotificationModal/CategoryList/type.ts
  src/Components/NotificationModal/NotificationHeader/index.tsx
  src/Components/NotificationModal/NotificationHeader/style.ts
  src/Components/NotificationModal/NotificationHeader/type.ts
  src/Components/NotificationModal/NotificationItem/index.tsx
  src/Components/NotificationModal/NotificationItem/style.ts
  src/Components/NotificationModal/NotificationItem/type.ts
  src/Components/NotificationModal/NotificationList/index.tsx
  src/Components/NotificationModal/NotificationList/style.ts
  src/Components/NotificationModal/NotificationList/type.ts
  src/Components/NotificationModal/filterNotification.ts
  src/Components/NotificationModal/index.tsx
  src/Components/NotificationModal/style.ts
  src/Components/NotificationModal/type.ts
  src/Constants/defaultUserImage.ts
  src/Constants/queryKeys.ts
  src/Pages/HomePage/index.tsx
  src/Utils/calculateDays.ts
Labels: Feat

#60 Fix: Header에 가려지는 이슈 해결
  src/Components/Common/Header/HeaderTab/LinkButton/index.tsx
  src/Components/Common/Header/HeaderTab/ModalButton/index.tsx
  src/Components/Common/Header/style.ts
Labels: Fix

#55 Feat: 포스트 상세 페이지 모달 및 파생 모달 레이아웃 기본 동작 구현
  src/Components/Common/Modal/index.tsx
  src/Components/Common/PostCard/index.tsx
  src/Components/Common/PostCard/style.ts
  src/Components/Common/PostCard/type.ts
  src/Components/Common/UserCard/index.tsx
  src/Components/Common/UserCard/type.ts
  src/Constants/queryKeys.ts
  src/Constants/userRole.ts
  src/Pages/DetailPage/PostDetailModal/PostDotModal/index.tsx
  src/Pages/DetailPage/PostDetailModal/PostDotModal/postDotModalConst.ts
  src/Pages/DetailPage/PostDetailModal/PostDotModal/style.ts
  src/Pages/DetailPage/PostDetailModal/PostDotModal/type.ts
  src/Pages/DetailPage/PostDetailModal/index.tsx
  src/Pages/DetailPage/PostDetailModal/style.ts
  src/Pages/DetailPage/PostDetailModal/type.ts
  src/Pages/DetailPage/index.tsx
  src/Pages/HomePage/index.tsx
  src/Routes/Router.tsx
Labels: Feat

#61 Feat: 채널 생성 모달 및 api 로직 구현 및 일부 수정사항 변경
  src/Components/Common/Header/HeaderTab/index.tsx
  src/Pages/DirectMessagePage/index.tsx
  src/Pages/HomePage/AddChannelModal/index.tsx
  src/Pages/HomePage/AddChannelModal/style.ts
  src/Pages/HomePage/AddChannelModal/type.ts
  src/Pages/HomePage/index.tsx
  src/Pages/HomePage/style.ts
  src/Routes/ModalRouter.tsx
  src/Routes/Router.tsx
Labels: Feat, Fix

#59 Feat: 사용자 상세 페이지 레이아웃 및 api 연동
  src/Components/Common/ImageCard/index.tsx
  src/Components/Common/ImageCard/style.ts
  src/Components/Common/ImageCard/type.ts
  src/Components/Profile/ProfileInfo/FollowInfo/index.tsx
  src/Components/Profile/ProfileInfo/FollowInfo/style.ts
  src/Components/Profile/ProfileInfo/FollowInfo/type.ts
  src/Components/Profile/ProfileInfo/MyProfileInfo/index.tsx
  src/Components/Profile/ProfileInfo/UserProfileInfo/index.tsx
  src/Components/Profile/ProfileInfo/index.tsx
  src/Components/Profile/ProfileInfo/style.ts
  src/Components/Profile/ProfileInfo/type.ts
  src/Components/Profile/ProfilePost/MyProfilePost/index.tsx
  src/Components/Profile/ProfilePost/MyProfilePost/style.ts
  src/Components/Profile/ProfilePost/MyProfilePost/type.ts
  src/Components/Profile/ProfilePost/UserProfilePost/index.tsx
  src/Components/Profile/ProfilePost/UserProfilePost/style.ts
  src/Components/Profile/ProfilePost/UserProfilePost/type.ts
  src/Components/Profile/ProfilePost/index.tsx
  src/Components/Profile/ProfilePost/style.ts
  src/Components/Profile/ProfilePost/type.ts
  src/Pages/ProfilePage/index.tsx
  src/Pages/ProfilePage/style.ts
  src/Routes/Router.tsx
Labels: Feat

#62 Refactor: 다이렉트 메세지 페이지 반응형 UI 적용 및 리팩토링
  src/Components/Common/UserCard/index.tsx
  src/Components/Common/UserCard/style.ts
  src/Components/Common/UserCard/type.ts
  src/Components/DirectMessage/ConversationList/index.tsx
  src/Components/DirectMessage/ConversationList/style.ts
  src/Components/DirectMessage/ConversationList/type.ts
  src/Components/DirectMessage/MessageItem/index.tsx
  src/Components/DirectMessage/MessageItem/style.ts
  src/Components/DirectMessage/MessageItem/type.ts
  src/Components/DirectMessage/MessageList/index.tsx
  src/Components/DirectMessage/MessageList/style.ts
  src/Components/DirectMessage/MessageList/type.ts
  src/Components/DirectMessage/MessageModal/index.tsx
  src/Components/DirectMessage/MessageModal/style.ts
  src/Components/DirectMessage/MessageModal/type.ts
  src/Components/DirectMessage/Skeleton/index.tsx
  src/Pages/DirectMessagePage/index.tsx
  src/Pages/DirectMessagePage/style.ts
  src/Styles/Animation.ts
Labels: Feat, Refactor

#63 Feat: 사용자 검색 기능 개발
  src/Components/Common/SearchBar/type.ts
  src/Components/Common/SkeletonList/style.ts
  src/Components/Login/LoginForm/index.tsx
  src/Components/UserManager/UserItem/index.tsx
  src/Components/UserManager/UserItem/style.ts
  src/Components/UserManager/UserItem/type.ts
  src/Components/UserManager/UserList/index.tsx
  src/Components/UserManager/UserList/style.ts
  src/Components/UserManager/UserList/type.ts
  src/Components/UserManager/UserSearchForm/index.tsx
  src/Components/UserManager/index.tsx
  src/Components/UserManager/style.ts
  src/Components/UserManager/validateSearchUser.ts
  src/Constants/queryKeys.ts
  src/Hooks/UseForm/index.ts
Labels: Feat

#65 Feat: 비밀번호 변경 기능
  src/Components/EditPassword/PasswordForm/index.tsx
  src/Components/EditPassword/PasswordForm/style.ts
  src/Components/EditPassword/PasswordForm/type.ts
  src/Components/EditPassword/PasswordForm/validatePassword.tsx
  src/Pages/EditPasswordPage/PasswordModal/index.tsx
  src/Services/Auth/index.ts
Labels: Feat

#67 Feat: 포스트 및 유저 검색 기능
  src/Components/Base/Avatar/index.tsx
  src/Components/Base/Avatar/type.ts
  src/Components/Base/Button/style.ts
  src/Components/SearchModal/SearchBar/index.tsx
  src/Components/SearchModal/SearchBar/style.ts
  src/Components/SearchModal/SearchBar/type.ts
  src/Components/SearchModal/SearchPostList/index.tsx
  src/Components/SearchModal/SearchPostList/style.ts
  src/Components/SearchModal/SearchPostList/type.ts
  src/Components/SearchModal/SearchUserList/index.tsx
  src/Components/SearchModal/SearchUserList/style.ts
  src/Components/SearchModal/SearchUserList/type.ts
  src/Components/SearchModal/index.tsx
  src/Components/SearchModal/style.ts
  src/Components/SearchModal/type.ts
  src/Pages/SearchPage/SearchModal/index.tsx
  src/Pages/SearchPage/index.tsx
Labels: Feat

#64 Feat: 포스트 작성/수정 모달 구현
  src/Components/Base/Spinner/style.ts
  src/Components/Common/DropDown/index.tsx
  src/Components/Common/DropDown/type.ts
  src/Components/Common/Header/HeaderTab/index.tsx
  src/Components/Common/ImageUpload/index.tsx
  src/Components/Common/ImageUpload/style.ts
  src/Components/Common/ImageUpload/type.ts
  src/Components/Common/Modal/AddOrEditPostModal/AsideHeader/index.tsx
  src/Components/Common/Modal/AddOrEditPostModal/AsideHeader/style.ts
  src/Components/Common/Modal/AddOrEditPostModal/AsideHeader/type.ts
  src/Components/Common/Modal/AddOrEditPostModal/TitleEditor/index.tsx
  src/Components/Common/Modal/AddOrEditPostModal/TitleEditor/style.ts
  src/Components/Common/Modal/AddOrEditPostModal/TitleEditor/type.ts
  src/Components/Common/Modal/AddOrEditPostModal/index.tsx
  src/Components/Common/Modal/AddOrEditPostModal/style.ts
  src/Components/Common/Modal/AddOrEditPostModal/type.ts
  src/Components/Common/Modal/AddOrEditPostModal/validatePostField.ts
  src/Constants/queryKeys.ts
  src/Pages/AddOrEditPostPage/index.tsx
  src/Pages/AddPostPage/PostModal/index.tsx
  src/Pages/AddPostPage/index.tsx
  src/Pages/DetailPage/PostDetailModal/PostDotModal/index.tsx
  src/Pages/index.ts
  src/Routes/ModalRouter.tsx
Labels: Feat

#69 Feat: 메인페이지, 포스트 상세 페이지에서 팔로우 동작 api 연결 및 관련 커스텀 훅 생성
  src/Components/Common/PostCard/index.tsx
  src/Components/Common/PostCard/type.ts
  src/Constants/queryKeys.ts
  src/Hooks/Api/Follow/index.ts
  src/Hooks/Api/Like/index.ts
  src/Pages/DetailPage/PostDetailModal/PostDotModal/style.ts
  src/Pages/DetailPage/PostDetailModal/index.tsx
  src/Pages/DetailPage/PostDetailModal/type.ts
  src/Pages/DetailPage/index.tsx
  src/Pages/HomePage/index.tsx
Labels: Feat

#70 Feat: 댓글 기능 api 연결 및 유저 페이지 이동 구현
  src/Components/Common/Modal/AddOrEditPostModal/index.tsx
  src/Components/Common/PostCard/index.tsx
  src/Components/Common/PostCard/type.ts
  src/Components/Common/UserCard/index.tsx
  src/Components/Common/UserCard/type.ts
  src/Hooks/Api/Comment/index.ts
  src/Hooks/Api/Like/index.ts
  src/Hooks/Api/Notification/index.ts
  src/Pages/DetailPage/PostDetailModal/PostDotModal/index.tsx
  src/Pages/DetailPage/PostDetailModal/PostDotModal/style.ts
  src/Pages/DetailPage/PostDetailModal/index.tsx
  src/Pages/DetailPage/PostDetailModal/style.ts
  src/Pages/DetailPage/index.tsx
  src/Pages/HomePage/index.tsx
  src/Pages/HomePage/style.ts
Labels: Feat

#71 Feat: 알림 읽기 기능 개발
  src/Components/Common/Header/HeaderTab/LinkButton/index.tsx
  src/Components/Common/Header/HeaderTab/LinkButton/type.ts
  src/Components/Common/Header/HeaderTab/ModalButton/index.tsx
  src/Components/Common/Header/HeaderTab/ModalButton/type.ts
  src/Components/Common/Header/HeaderTab/filterNotificationLength.ts
  src/Components/Common/Header/HeaderTab/index.tsx
  src/Components/NotificationModal/NotificationItem/index.tsx
  src/Components/NotificationModal/NotificationItem/style.ts
  src/Components/NotificationModal/NotificationItem/type.ts
  src/Components/NotificationModal/NotificationList/index.tsx
  src/Components/NotificationModal/NotificationList/type.ts
  src/Components/NotificationModal/filterNotification.ts
  src/Components/NotificationModal/index.tsx
  src/Components/NotificationModal/style.ts
  src/Components/NotificationModal/type.ts
  src/Styles/Theme.ts
  src/Types/NotificationType.ts
  src/Utils/calculateDays.ts
  src/Utils/calculateTime.ts
Labels: Feat

#75 Feat: 다크 모드 기능 버튼 구현
  src/App.tsx
  src/Components/DarkMode/index.tsx
  src/Components/DarkMode/style.ts
  src/Components/DarkMode/type.ts
  src/Components/UserManager/UserItem/style.ts
  src/Components/UserManager/index.tsx
  src/Styles/Animation.ts
  src/Styles/Global.ts
Labels: Feat

#76 Fix: MessageReceiver 모듈 경로 수정
  src/Components/NotificationModal/NotificationItem/index.tsx
Labels: Fix

#72 Feat: 팔로우 모달 구현
  src/Components/Common/UserCard/index.tsx
  src/Components/Common/UserCard/type.ts
  src/Components/DirectMessage/ConversationList/index.tsx
  src/Components/DirectMessage/MessageList/index.tsx
  src/Components/DirectMessage/MessageModal/index.tsx
  src/Components/FollowModal/index.tsx
  src/Components/FollowModal/style.ts
  src/Components/FollowModal/type.ts
  src/Components/Profile/ProfileInfo/FollowInfo/index.tsx
  src/Components/Profile/ProfileInfo/FollowInfo/type.ts
  src/Components/Profile/ProfileInfo/index.tsx
  src/Components/Profile/ProfileInfo/type.ts
  src/Constants/queryKeys.ts
  src/Hooks/Api/Auth/index.ts
  src/Hooks/Api/User/index.ts
  src/Hooks/useDebouncedSearch/index.ts
  src/Hooks/useDebouncedSearch/type.ts
  src/Hooks/useResize/index.ts
  src/Pages/DirectMessagePage/index.tsx
  src/Pages/ProfilePage/index.tsx
Labels: Feat

#79 Fix: User Card 이름 및 아바타 클릭 오류 및 다이렉트 메시지 버그 수정
  src/Components/Common/UserCard/index.tsx
  src/Components/DirectMessage/ConversationList/index.tsx
  src/Components/DirectMessage/ConversationList/style.ts
  src/Hooks/useResize/index.ts
  src/Pages/DetailPage/PostDetailModal/index.tsx
  src/Pages/DirectMessagePage/index.tsx
Labels: Fix

#80 Feat: 메인 페이지와 상세페이지 스켈레톤 UI 추가
  src/Components/Common/PostCard/PostCardSkeleton/index.tsx
  src/Components/Common/PostCard/PostCardSkeleton/style.ts
  src/Components/Common/PostCard/style.ts
  src/Components/Common/UserCard/index.tsx
  src/Pages/DetailPage/PostDetailModal/PostDetailSkeleton/index.tsx
  src/Pages/DetailPage/PostDetailModal/PostDetailSkeleton/style.ts
  src/Pages/DetailPage/PostDetailModal/index.tsx
  src/Pages/DetailPage/PostDetailModal/style.ts
  src/Pages/HomePage/index.tsx
Labels: Feat

#81 Fix: refetch 관련 수정사항 반영
  src/Components/Profile/ProfileInfo/UserProfileInfo/index.tsx
  src/Components/Profile/UpdateImageModal/index.tsx
  src/Components/Profile/UpdateNameModal/index.tsx
  src/Pages/ProfilePage/index.tsx
Labels: Fix

#82 Refactor: 다이렉트 메세지 리액트 쿼리 커스텀 훅 분리 및 읽기 기능 추가
  src/Components/DirectMessage/ConversationList/index.tsx
  src/Components/DirectMessage/MessageModal/index.tsx
  src/Components/NotificationModal/NotificationItem/index.tsx
  src/Constants/queryKeys.ts
  src/Hooks/Api/Message/index.ts
  src/Hooks/Api/Search/index.ts
  src/Pages/DetailPage/PostDetailModal/index.tsx
Labels: Refactor

#83 Chore: Create main.yml
  .github/workflows/main.yml
Labels: chore

#84 Fix: 로그인 페이지 뒤로가기 버튼 2번 클릭 시 이동하는 버그 수정
  src/Components/Common/Header/HeaderTab/LoginButton/index.tsx
  src/Components/Common/Header/HeaderTab/index.tsx
Labels: Fix

#85 Design: 다크 모드 버튼 왼쪽으로 이동
  src/Components/DarkMode/style.ts
Labels: Design

#88 Fix: 알림 기능 수정
  src/Components/Common/Header/HeaderTab/index.tsx
  src/Components/NotificationModal/CategoryItem/style.ts
  src/Components/NotificationModal/CategoryList/style.ts
  src/Components/NotificationModal/filterNotification.ts
  src/Components/NotificationModal/index.tsx
  src/Components/NotificationModal/style.ts
  src/Hooks/UseClickAway/index.ts
  src/Styles/Animation.ts
Labels: Fix, Design

#90 Design: 메인 페이지 및 상세 페이지 반응형 디자인 수정
  src/Components/Common/Header/HeaderLogo/index.tsx
  src/Components/Common/PostCard/PostCardSkeleton/index.tsx
  src/Components/Common/PostCard/PostCardSkeleton/style.ts
  src/Components/NotificationModal/NotificationItem/index.tsx
  src/Components/UserManager/style.ts
  src/Constants/storage.ts
  src/Pages/DetailPage/PostDetailModal/PostDotModal/index.tsx
  src/Pages/DetailPage/PostDetailModal/PostDotModal/style.ts
  src/Pages/DetailPage/PostDetailModal/PostDotModal/type.ts
  src/Pages/DetailPage/PostDetailModal/index.tsx
  src/Pages/DetailPage/PostDetailModal/style.ts
  src/Pages/HomePage/index.tsx
  src/Pages/HomePage/style.ts
  src/Stores/Channel/index.ts
  src/Stores/Channel/type.ts
  src/Stores/index.ts
Labels: Feat, Fix, Design

#87 Feat: 모바일 환경 반응형 헤더 구현
  src/Components/Common/DropDownOnlyOption/index.tsx
  src/Components/Common/DropDownOnlyOption/style.ts
  src/Components/Common/DropDownOnlyOption/type.ts
  src/Components/Common/Header/Hamburger/index.tsx
  src/Components/Common/Header/Hamburger/style.ts
  src/Components/Common/Header/HeaderLogo/style.ts
  src/Components/Common/Header/HeaderTab/index.tsx
  src/Components/Common/Header/HeaderTab/style.ts
  src/Components/Common/Header/index.tsx
  src/Components/Common/Header/style.ts
  src/Components/SearchModal/index.tsx
  src/Components/SearchModal/style.ts
  src/Styles/Animation.ts
Labels: Feat

#92 Fix: 유저 관리 컴포넌트 스켈레톤 UI 적용
  src/Components/UserManager/index.tsx
Labels: Fix

#93 Design:
  src/Components/NotificationModal/CategoryList/style.ts
  src/Components/NotificationModal/style.ts
Labels: Design

#86 Fix: 포스트 작성, 수정 관련 이슈들
  src/Components/Common/ImageUpload/index.tsx
  src/Components/Common/Modal/AddOrEditPostModal/index.tsx
  src/Pages/AddOrEditPostPage/index.tsx
Labels: Fix

#89 Refactor: 유저 프로필 페이지 반응형, 스켈레톤 추가 및 모달 오류 해결
  src/Components/Common/Header/HeaderTab/index.tsx
  src/Components/Common/Modal/AlarmModal/index.tsx
  src/Components/Common/Modal/index.tsx
  src/Components/Common/Modal/style.ts
  src/Components/Profile/ProfileInfo/index.tsx
  src/Components/Profile/ProfileInfo/style.ts
  src/Components/Profile/ProfileInfo/type.ts
  src/Components/Profile/ProfilePost/MyProfilePost/index.tsx
  src/Components/Profile/ProfilePost/MyProfilePost/type.ts
  src/Components/Profile/ProfilePost/UserProfilePost/index.tsx
  src/Components/Profile/ProfilePost/UserProfilePost/style.ts
  src/Components/Profile/ProfilePost/UserProfilePost/type.ts
  src/Components/Profile/ProfilePost/index.tsx
  src/Components/Profile/ProfilePost/style.ts
  src/Components/Profile/ProfilePost/type.ts
  src/Components/Profile/UpdateImageModal/index.tsx
  src/Components/Profile/UpdateNameModal/index.tsx
  src/Pages/EditPasswordPage/PasswordModal/index.tsx
  src/Pages/ProfilePage/index.tsx
  src/Pages/ProfilePage/style.ts
  src/Utils/modalScroll.ts
Labels: Refactor, Design

#91 Refactor: 다이렉트 메세지 페이지 QA 수정사항 반영
  src/Components/Common/UserCard/index.tsx
  src/Components/Common/UserCard/style.ts
  src/Components/Common/UserCard/type.ts
  src/Components/DirectMessage/ConversationList/index.tsx
  src/Components/DirectMessage/ConversationList/type.ts
  src/Components/DirectMessage/MessageList/index.tsx
  src/Components/DirectMessage/MessageList/style.ts
  src/Components/DirectMessage/MessageList/type.ts
  src/Components/DirectMessage/MessageModal/index.tsx
  src/Components/DirectMessage/MessageModal/type.ts
  src/Components/DirectMessage/Skeleton/index.tsx
  src/Components/DirectMessage/Skeleton/style.ts
  src/Components/NotificationModal/NotificationItem/index.tsx
  src/Components/Profile/ProfileInfo/UserProfileInfo/index.tsx
  src/Hooks/Api/Message/index.ts
  src/Hooks/Api/Notification/index.ts
  src/Pages/DetailPage/PostDetailModal/index.tsx
  src/Pages/DirectMessagePage/index.tsx
  src/Stores/MessageReceiver/index.ts
  src/Stores/MessageReceiver/type.ts
Labels: Refactor

#94 Design: 모바일 카테고리 드롭다운 구현
  src/Components/Common/Header/HeaderLogo/index.tsx
  src/Pages/HomePage/index.tsx
  src/Pages/HomePage/style.ts
  src/Styles/Global.ts
Labels: Feat

#96 Refactor: getChannel API 함수 내부에서 채널 이름이 한글인 경우 인코딩 작업 추가
  src/Services/Channel/index.ts
Labels: Refactor

#95 Feat: 비회원이 회원전용 기능에 접근 시 로그인 페이지로 유도하는 Alert 추가
  src/Components/Base/Input/style.ts
  src/Components/Common/Alert/index.tsx
  src/Components/Common/Alert/style.ts
  src/Components/Common/Alert/type.ts
  src/Components/Common/Modal/AddOrEditPostModal/index.tsx
  src/Components/Profile/ProfileInfo/UserProfileInfo/index.tsx
  src/Constants/nonAuthUser.ts
  src/Pages/AddOrEditPostPage/index.tsx
  src/Pages/DetailPage/PostDetailModal/index.tsx
  src/Pages/HomePage/index.tsx
  src/Types/Request/index.ts
Labels: Feat

#97 Fix: 팔로우 모달, 다이렉트 메세지 모달 타이핑 시 스켈레톤 자연스럽게 유지
  src/Components/Common/Header/HeaderTab/index.tsx
  src/Components/DirectMessage/MessageModal/index.tsx
  src/Components/FollowModal/index.tsx
  src/Hooks/Api/Search/index.ts
  src/Hooks/useDebouncedSearch/index.ts
  src/Hooks/useDebouncedSearch/type.ts
  src/Hooks/useIsTyping/index.ts
Labels: Fix

#98 Fix: 비로그인 시 다크모드 적용되지 않는 문제
  src/Components/Common/DropDown/style.ts
  src/Components/Common/Header/Hamburger/index.tsx
Labels: Fix

#99 Fix: 팔로우모달 흰 점 제거
  src/Components/FollowModal/style.ts
Labels: Fix

#101 Fix: 포스트 추가 모달에서 Channel 드롭다운 매핑 문제 해결
  src/Components/Common/Modal/AddOrEditPostModal/AsideHeader/index.tsx
Labels: Fix

#102 Merge: 1차 배포 후 수정사항 적용
  src/App.tsx
  src/Components/Common/Modal/AddOrEditPostModal/AsideHeader/index.tsx
  src/Components/Common/SearchBar/index.tsx
  src/Components/Common/UserCard/index.tsx
  src/Pages/HomePage/index.tsx
Labels: Merge

#103 Fix: 팔로우 연타 시 중복으로 들어가던 현상 debounce로 해결
  src/Components/FollowModal/index.tsx
  src/Components/Profile/ProfileInfo/UserProfileInfo/index.tsx
Labels: Fix

#104 Docs: README.md 파일 작성
  README.md
Labels: Docs

#105 Merge: dev -> main 2차 피드백 수정 및 README.md 수정
  README.md
  src/Components/FollowModal/index.tsx
  src/Components/Profile/ProfileInfo/UserProfileInfo/index.tsx
  src/Routes/Router.tsx
Labels: Merge
